sync_type = "git"
sync_remote = "https://github.com/mwoyuan/dotfiles.git"

[dots."~/works/playground/.testrc"]
type = "file"
last_sha1_check = 1567351535
sha1 = "da39a3ee5e6b4b0d3255bfef95601890afd80709"
